name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]  # Removed 23.x and 24.x as they're not LTS
      fail-fast: false  # Continue with other versions if one fails

    steps:
    - uses: actions/checkout@v4  # Updated to v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4  # Updated to v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # Added caching

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium

    - name: Run tests with coverage
      run: npm run test:coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage/lcov.info
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: shane-reaume/playwright-mongodb-reporter